<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rahul" ignored="0" name="BankigAppTest" tests="7" failures="3" timestamp="01 May 2019 18:04:25 GMT" time="397.122" errors="0">
  <testcase name="loginTest" time="33.879" classname="com.demo.testCases.TC_LoginTest_001"/>
  <testcase name="loginDDT" time="34.47" classname="com.demo.testCases.TC_LoginDDT_002"/>
  <testcase name="loginDDT" time="12.216" classname="com.demo.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demo.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="12.269" classname="com.demo.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demo.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="24.754" classname="com.demo.testCases.TC_LoginDDT_002"/>
  <testcase name="loginDDT" time="12.305" classname="com.demo.testCases.TC_LoginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demo.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="addNewCustomer" time="41.757" classname="com.demo.testCases.TC_AddCustomerTest_003"/>
</testsuite> <!-- BankigAppTest -->
